version: "3"
services:
  video:
    build:
      context: "video"
      args:
        # for CPU
        # BASE_IMAGE: "ubuntu:20.04"
        # COMPUTING_DEVICE: "cpu"
        # for GPU
        BASE_IMAGE: "nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04"
        COMPUTING_DEVICE: "gpu"
    volumes:
      - "./video:/mnt/workspace" # DEBUG:
    working_dir: "/mnt/workspace" # DEBUG:
    command: "/bin/bash" # DEBUG:
